### ISSUE TITLE
Stop copying

### ISSUE THREAD

**Issue by flaxues** [EndKingdom/Some-plugins-we-used-in-EndKingdom-Server#4]
@EndKingdom-Owner You are uploading the wrong way!

You are copying the content of the .phar which is the WRONG way of doing it! Thats why they don't work!

**Comment by matthew4444** [comment]
Hey i UPLOADED THE PLUGINS TO A FOLDER IN MEDIAFIRE AND IM NOT USING A .ZIP FILR THIS TIME

**Comment by flaxues** [comment]
Yeah I know @matthew4444 I'm translating them!

**Comment by EndKingdom-Owner** [comment]
Hey flaxues

**Comment by EndKingdom-Owner** [comment]
You want to work at the ender auth

**Comment by matthew4444** [comment]
ok,falxues
And enderowner yes

**Comment by flaxues** [comment]
Call me Matthew :P

**Comment by EndKingdom-Owner** [comment]
Kk

**Comment by matthew4444** [comment]
but my name is matthew james pitsicalis -.-

**Comment by EndKingdom-Owner** [comment]
Guys we need to at the ender auth nothing else can you guys do that

**Comment by matthew4444** [comment]
ya

**Comment by EndKingdom-Owner** [comment]
What about you flaxues/matthew 2

**Comment by flaxues** [comment]
@EndKingdom-Owner Would you make like a list with thing you want in enderauth?

**Comment by matthew4444** [comment]
Ya

**Comment by matthew4444** [comment]
hey

**Comment by matthew4444** [comment]
1. Custom login messages
2. Add in config.yml if u want to login with typing ur password when u join,insted of /login
3. ideas plz

**Comment by matthew4444** [comment]
Hello

**Comment by matthew4444** [comment]
Hello

**Comment by flaxues** [comment]
@matthew4444 I'm working on fixing the corrupted phars endkingdom uploaded

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
tell me when ur done plz

**Comment by matthew4444** [comment]
Endkingdom owner just left to go to a movie,the person said it to me in privite chat

**Comment by flaxues** [comment]
Private chat? maybe we can go in the chatbox you made

**Comment by matthew4444** [comment]
Ok

**Comment by matthew4444** [comment]
https://gitter.im/flaxues

**Comment by matthew4444** [comment]
Hello @flaxues

**Comment by matthew4444** [comment]
Hello

**Comment by matthew4444** [comment]
Hello

**Comment by matthew4444** [comment]
Hi

**Comment by flaxues** [comment]
http://matzserver.net76.net/old_site/old_site/assets/htmlfiles/chat.html

**Comment by matthew4444** [comment]
Ok

**Comment by EndKingdom-Owner** [comment]
This what i want on this auth 1: messages 2: email 3: register confirm 4: change password 5: change password confirm 6:  no moving 7: you can chat after logged in or registerd 8: you can only do /help but you cant do anything still 9: kick if not logged or registerd in after 5 min 10: timeout like you got kicked because you didnt register or logged in DONE

**Comment by matthew4444** [comment]
Did u finish tHe movie
